<?php

/**
 *	Name:			Changelogger
 *	Description: 	Create easily changelog files for your projects
 *
 *	Author:			ANEX
 *	Author URL:		http://anex.at
 *
 *	Version:		1.0.0
 */

if( file_exists('app/settings.php' ) )
	require_once( 'app/settings.php' );
	
if( file_exists('app/functions.php' ) )
	require_once( 'app/functions.php' );
	
if( file_exists('app/debug.php' ) )
	require_once( 'app/debug.php' );
	
//====================================================================//
// Do not edit below here
//====================================================================//

$errorstack = array();



//$version = APP_VERSION;

$x = isset( $_GET['x'] ) ? $_GET['x'] : FALSE;

if( isset( $_POST['password'] ) ) {
	
	if( $_POST['password'] == PASSWORD ) { 
		setcookie( APP_TITLE . '_login', sha256( PASSWORD . $_SERVER['REMOTE_ADDR'] ), NULL, '/', '.' . str_ireplace( 'www.', '', $_SERVER['SERVER_NAME'] ) ); 
		header( "Location: " . $_SERVER['PHP_SELF'] ); 
		exit;
	} else { 
		header( "Location: " . $_SERVER['PHP_SELF'] . "?x=wp" ); 
		exit; 
	}
	
}
?>

<!DOCTYPE html>
<html>

    <head>
    
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="robots" content="noindex, nofollow" />
        
        <title><?php echo changelogger_info( 'name' ); ?></title>
        
        <link rel="stylesheet" id="uikit-css"  href="<?php echo APP_BASE_URL; ?>/app/assets/css/uikit/uikit.min.css" type="text/css" media="all" />
        <link rel="stylesheet" id="uikit-css"  href="<?php echo APP_BASE_URL; ?>/app/assets/css/uikit/addons/uikit.addons.min.css" type="text/css" media="all" />
        
        <link rel="stylesheet" id="changelogger-css"  href="<?php echo APP_BASE_URL; ?>/app/assets/css/base.css?<?php echo changelogger_info( 'version' ); ?>" type="text/css" media="all" />
        
	</head>
    
<?php
if(isset($_COOKIE[APP_TITLE . '_login'])) $login = $_COOKIE[APP_TITLE . '_login']; else $login = 'no';

if(MODE == 'private') {
	if($login != sha256(PASSWORD . $_SERVER['REMOTE_ADDR'])) {
		?>
		<body>
			 <div id="content">
			 	<div id="form">
			 		<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
			 			<table class="tbl">
			 			 <tr>
			 			   <td><?php echo APP_TITLE ?> - ChangeLog</td>
			 			   <td class="alright"><?php if($x == 'wp') echo '<span class="error">Try Again</span>'; else echo 'Login'; ?>: <input style="width:150px; margin-left: 20px;" type="password" name="password" placeholder="Password" /></td>
			 			 </tr>
			 			</table>
			 		</form>
			 	</div>
			 </div>
		</body>
		</html>
		<?php
		exit;
	}
}

//!Generate the change log if need be
$logfile = CHANGELOG_PATH . 'changelog-' . strtolower( APP_TITLE ) . '.txt';

//!load vars
$log = array();
$error = FALSE;
$lastType = 'update';
$showFullPaths = isset($_GET['fullPaths']) ? $_GET['fullPaths'] : 0;
$showRE = isset($_GET['showRE']) ? $_GET['showRE'] : 0;
$anchor = isset($_GET['anchor']) ? explode('+', str_ireplace('_', ' ', $_GET['anchor'])) : FALSE;
$q = isset($_GET['q']) ? str_ireplace(' ', '(.*)', $_GET['q']) : '';

// generate file */
if( !file_exists( $logfile ) )
	file_put_contents( $logfile, '#' . APP_TITLE . ' - Changelog. Generated by Changelogger v ' . changelogger_info( 'version' ) . ' on ' . date( "Y-m-d H:i:s" ) );

//!Load User Details
if(isset($_COOKIE[APP_TITLE . '_user'])) {
	$userdata = explode('#', base64_decode($_COOKIE[APP_TITLE . '_user']));
	$name = $userdata[0];
	$email = $userdata[1];
	$project = "";
	$version = "";
}
else {
	$name = "";
	$email = "";
	$project = "";
	$version = "";
}

//!Read File
if(!changelogger_errored()) {
	
	//load log
	$file = file($logfile);
	$REmatch = array();

	//!Read file
	foreach($file as $num => $logLine) {

		//find entries
		if(preg_match("/^[0-9\-]{10}/", $logLine)) {
			$entry = explode("  ", $logLine);
			$date = $entry[0];
			$name = $entry[3];
			$email = str_ireplace(array("<", ">"), '', trim($entry[4]));
			$project = $entry[1];
			$version = $entry[2];

			if(!isset($log[$date])) $log[$date] = array();
			$log[$date][$name]['id'] = array('email' => $email);

			$currentDate = $date;
			$currentName = $name;
		}
		//find nodes
		elseif (preg_match("/^\t\*/", $logLine)) {
			$node = explode(' [', str_ireplace("\t* ", '', $logLine));
			$loc = reset($node);
			$loc = explode(":", trim($loc));
			$str = end($node);
			$str = explode("] : ", trim($str));

			$text = str_ireplace("\'", "'", trim($str[1]));

			//Find RE's
			if (preg_match("/re:[a-z0-9\-\+\_]+/i", $text, $match)) {
				$REdata = explode('+', str_ireplace(array('re:', '_'), array('', ' '), $match[0]));

				if (!in_array('', $REdata)) {
					if(!isset($REmatch[$REdata[0]])) $REmatch[$REdata[0]] = array();
					if(!isset($REmatch[$REdata[0]][$REdata[1]])) $REmatch[$REdata[0]][$REdata[1]] = array();
					$REmatch[$REdata[0]][$REdata[1]][$REdata[2]] = TRUE;
				}
			}
			$log[$currentDate][$currentName][] = array(
				'path' 		=> $loc[0], 
				'line' 		=> $loc[1], 
				'type' 		=> $str[0], 
				'text' 		=> $text
			);
		}


	}
	$log = array_reverse($log);

}

//! Write
if( isset( $_POST['sub'] ) ) {
	
	$name 		= isset($_POST['name']) ? $_POST['name'] : "";
	$email 		= isset($_POST['email']) ? $_POST['email'] : "";
	$project 	= isset($_POST['project']) ? $_POST['project'] : "";
	$version 	= isset($_POST['version']) ? $_POST['version'] : "";
	$type 		= isset($_POST['type']) ? $_POST['type'] : "";
	$lastType 	= $type;
	$path 		= isset($_POST['path']) ? $_POST['path'] : "Global";
	$line 		= isset($_POST['line']) ? $_POST['line'] : "N/A";
	$text 		= isset($_POST['text']) ? $_POST['text'] : "";

	//Remember && Validate
	if($name != "" && $email != "") setcookie(APP_TITLE . '_HMCLuser', base64_encode($name . '#' . $email), NULL, '/', '.' . str_ireplace('www.', '', $_SERVER['SERVER_NAME']));
	else changelogger_error('You didn\'t provide a name or email');
	
	if($text == "") changelogger_error('You forgot to enter a log message');
	
	//!write to change log
	if(!changelogger_errored()) {

		$log[date('Y-m-d')][$name]['id'] = array('email' => $email);
		$log[date('Y-m-d')][$name][] = array(
				'path' 		=> $path, 
				'line' 		=> $line, 
				'type' 		=> $type, 
				'text' 		=> str_ireplace(array("\'", '\"'), array("'", '"'), $text)
		);
		
		ksort($log);
		
		$toWrite = '';
		$fp = fopen($logfile, "w");
		foreach($log as $date => $users) {
			foreach($users as $name => $nodes) {
				$toWrite .= "\n" . $date . '  ' . $project . '  ' . $version . '  ' . $name . '  <' . $nodes['id']['email'] . '>' . "\n";
				unset($nodes['id']);

				foreach($nodes as $node) {
					$toWrite .= "\t" . '* [' . $node['type'] . '] : ' . $node['path'] . ':' . $node['line'] . ' : ' . $node['text'] . "\n";
				}
			}

		}
		fwrite($fp, str_ireplace(array("\'", '\"'), array("'", '"'), $toWrite));
		fclose($fp);
	}
}
?>
<body <?PHP if(isset($_GET['fillText'])) echo ' onload="document.getElementById(\'text\').focus();"'; ?>>

    <div id="messages" class="messages">
        <?php echo changelogger_output_errors() ?>
    </div>
    
    <div id="interface">
    
        <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="uk-form">
            
            <header>
                
                <div class="uk-grid">
                    <div class="uk-width-4-10">
                        <div id="logo">
                            <?php echo '<a href="' . $_SERVER['PHP_SELF'] . '">' . APP_TITLE . '</a>'; ?>
                        </div>
                    </div>
                    <div class="uk-width-3-10">
                    	<input type="text" name="name" placeholder="Name" value="<?php echo $name; ?>" class="uk-width-1-1" />
                    </div>
                    <div class="uk-width-3-10">
                    	<input type="text" name="email" placeholder="E-mail" value="<?php echo $email; ?>" class="uk-width-1-1">
                    </div>
                </div>
                
            </header>
    
            <main data-uk-sticky>
            
                <div class="uk-grid">
                    <div class="uk-width-5-10">
                    	<input type="text" name="project" placeholder="Project" value="<?php echo $project; ?>" class="uk-width-1-1 uk-form-large" />
                    </div>
                    <div class="uk-width-5-10">
                    	<input type="text" name="version" placeholder="Version" value="<?php echo $version; ?>" class="uk-width-1-1 uk-form-large">
                    </div>
                </div>
        
                <div class="uk-grid uk-margin-top">
                    <div class="uk-width-3-10">
                        <select name="type" class="uk-width-1-1 uk-form-large type" placeholder="Type">;
                        <?php
                        foreach( changelogger_types() as $type ) {
							
							if( $lastType == $type ) {
								$selected = ' selected="selected"';
							} else {
								$selected = '';
							}
							
							echo '<option value="' . $type . '"' . $selected . '>' . ucwords( $type ) . '</option>';
                        }
                        ?>
                        </select>
                    </div>
                    <div class="uk-width-5-10">
                        <input type="text" name="path" placeholder="File name" value="<?php if(isset($_GET['fillPath'])) echo $_GET['fillPath']; ?>" class="uk-width-1-1 uk-form-large" />
                    </div>
                    <div class="uk-width-2-10">
                        <input type="text" name="line" placeholder="Line" value="" class="uk-width-1-1 uk-form-large" />                    
                    </div>
                </div>
                <div class="uk-grid uk-margin-top">
                    <div class="uk-width-1-1">
                        <textarea name="text" id="text" rows="3" placeholder="Description" class="uk-width-1-1 uk-form-large"><?php if(isset($_GET['fillText'])) echo $_GET['fillText']; ?></textarea>
                    </div>
                </div>
                <div class="uk-grid uk-margin-top">
                    <div class="uk-width-1-1">
                        <input name="sub" type="submit" value="ADD" class="uk-button uk-button-primary uk-button-large uk-width-1-1" />
                    </div>
                </div>
                                                            
           </main>
           
        </form> 

		<?php
        
        krsort($log);
        
        //Regarding RE:
        $RElink = FALSE;
        
        if($anchor == FALSE) $useLog = $log;
        else {
            if($anchor[2] != '') {
                $useLog[$anchor[0]] = array($anchor[1] => array($log[$anchor[0]][$anchor[1]][$anchor[2]]));
                $useLog[$anchor[0]] = array($anchor[1] => array('id' => $log[$anchor[0]][$anchor[1]]['id'], $anchor[2] => $log[$anchor[0]][$anchor[1]][$anchor[2]]));
                $RElink = TRUE;
            }
            elseif($anchor[1] != '') $useLog[$anchor[0]] = array($anchor[1] => $log[$anchor[0]][$anchor[1]]);
            else $useLog[$anchor[0]] = $log[$anchor[0]];
        }
        ?>
        
        <div id="options">
            <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="get" class="uk-form">
            	<div class="uk-button-group" data-uk-button-checkbox>
					<?php if ($RElink == TRUE) { ?><a class="uk-button uk-button-small" href="<?php echo $_SERVER['PHP_SELF'] . '?fillText=RE:' . urlencode($_GET['anchor'] . ' ') . '&fillPath=' . urlencode($useLog[$anchor[0]][$anchor[1]][$anchor[2]]['path']); ?>">RE:Anchor</a><?php } ?>
                    <a class="uk-button uk-button-small" href="<?php echo $_SERVER['PHP_SELF'] . '?' . $_SERVER['QUERY_STRING']; ?>">Reload</a>
                    <?php if ($showRE == 0) echo '<a class="uk-button uk-button-small" href="' . $_SERVER['PHP_SELF'] . '?showRE=1&amp;fullPaths=' . $showFullPaths . '&amp;q=' . $q . '">Show Anchors</a>'; else echo '<a class="uk-button uk-button-small" href="' . $_SERVER['PHP_SELF'] . '?showRE=0&fullPaths=' . $showFullPaths . '&q=' . $q . '">Hide Anchors</a>'; ?>
                    <?php if ($showFullPaths == 0) echo '<a class="uk-button uk-button-small" href="' . $_SERVER['PHP_SELF'] . '?fullPaths=1&amp;showRE=' . $showRE . '&amp;q=' . $q . '">Full Paths</a>'; else echo '<a class="uk-button uk-button-small" href="' . $_SERVER['PHP_SELF'] . '?fullPaths=0&showRE=' . $showRE . '&q=' . $q . '">Short Paths</a>'; ?>
                    <a class="uk-button uk-button-small" data-uk-toggle="{target:'#log'}">Changelog</a>
                </div>

                <input type="search" name="q" value="<?php if ($q != '') echo str_ireplace('(.*)', ' ', $q); ?>" placeholder="Search ChangeLog" class="uk-align-right">
            </form>
            
        </div>
        
        
        <div id="log" class="uk-hidden">
        
        	<?php if(empty($log)) { ?>
            No Entries available
            <?php } ?>
        
			<?php
            //!make GUI
            foreach($useLog as $date => $users) {
                foreach($users as $name => $nodes) {
            
                    //Build Anchors
                    if($showRE == 1) {
                        $dateRE = '[<a href="' . $_SERVER['PHP_SELF'] . '?anchor=' . urlencode($date . '++') . '">#</a>]';
                        $dateNameRE = '[<a href="' . $_SERVER['PHP_SELF'] . '?anchor=' . urlencode($date . '+' . str_ireplace(' ' , '_', $name) . '+') . '">#</a>]';
                    }
                    else {
                        $dateRE = '';
                        $dateNameRE = '';
                    }
            
                    echo '<div class="uk-panel"><span class="entry">' . $date . '' . $dateRE . '  <a href="mailto:' . $nodes['id']['email'] . '">' . $name . '</a></span>' . $dateNameRE . '';
            
                    unset($nodes['id']);
            
                    echo '<ul class="uk-list uk-list-space">';
                    foreach ($nodes as $key => $node) {
                        if (preg_match("/$q/i", implode(' ', $node))) {
            
                            if ($showRE == 1) $dateNameNumRE = '[<a href="' . $_SERVER['PHP_SELF'] . '?anchor=' . urlencode($date . '+' . str_ireplace(' ' , '_', $name) . '+' . $key) . '">#</a>]';
                            else $dateNameNumRE = '';
            
                            //REed?
                            $REed = '';
                            if (isset($REmatch[$date][$name][$key])) { if ($REmatch[$date][$name][$key] == TRUE) $REed = ' class="re"'; }
            
                            echo '<li' . $REed . '>' . $dateNameNumRE ;
            
                            //show type
							if( $node['type'] ) {
								echo '<span class="badge badge-' . strtolower( $node['type'] ) . '">[' . $node['type'] . ']</span>';
							}
							
//                            if(strtolower($node['type']) == 'bug') echo '<span class="bug">[Bug]</span> ';
//                            elseif(strtolower($node['type']) == 'fix') echo '<span class="fix">[Fix]</span> ';
//                            elseif(strtolower($node['type']) == 'update') echo '<span class="update">[Update]</span> ';
//                            elseif(strtolower($node['type']) == 'note') echo '<span class="note">[Note]</span> ';
//                            elseif(strtolower($node['type']) == 'doc') echo '<span class="doc">[Doc]</span> ';
//                            elseif(strtolower($node['type']) == 'todo') echo '<span class="todo">[Todo]</span> ';
//                            else echo '<span class="unknown">[' . $node['title'] . ']</span> ';
            
                            //show text
                            if (preg_match("/re:[a-z0-9\-\+\_]+/i", $node['text'], $match)) { $node['text'] = str_ireplace($match[0], 'RE:[<a href="' . $_SERVER['PHP_SELF'] . '?anchor=' . urlencode(str_ireplace('re:', '', $match[0])) . '">#</a>]', $node['text']); }
            
                            if ($node['type'] == 'note') $font = 'italic'; else $font = 'inherit';
                            echo '<span>' . $node['text'] . '</span><br>';
			
							echo '<span class="log-entry-path-line uk-text-small">';
							
                            //show path
                            $eachPath2 = array();
                            $pathEcho = 'in <span class="path">';
            
                            if (stripos($node['path'], '&') === false) {
                                if ($showFullPaths == 0) {
                                    $path = explode("/", "//" . $node['path']);
                                    $pathEcho .= $path[(count($path)-2)] . '/' . end($path);
                                }
                                else $pathEcho .= $node['path'];
                            }
                            else {
                                $eachPathFull = explode(' & ', $node['path']);
                                foreach ($eachPathFull as $pathFull) {
                                    if ($showFullPaths == 0) {
                                        $pathFull = explode("/", "//" . $pathFull);
                                        $eachArr[] = $pathFull[(count($pathFull)-2)] . '/' . end($pathFull);
                                    }
                                    else $eachArr[] = $pathFull;
                                }
                                $pathEcho .= implode(' & ', $eachArr);
                            }
            
                            echo $pathEcho . '</span>';
            
                            //show line
                            if ($node['line'] != "") echo ' on line <span class="line">' . $node['line'] . '</span>';
                        
                            echo '</span>';
							
                            echo '</li>';
                        }
                    }
                    echo '</ul>';
                }
            
                echo '</div>';
            }
            ?>
            
        </div>
   
    
    </div>

	<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="<?php echo APP_BASE_URL; ?>/app/assets/js/uikit/uikit.min.js"></script>
    <script src="<?php echo APP_BASE_URL; ?>/app/assets/js/uikit/addons/notify.min.js"></script>
    <script src="<?php echo APP_BASE_URL; ?>/app/assets/js/uikit/addons/sticky.min.js"></script>
    <script src="<?php echo APP_BASE_URL; ?>/app/assets/js/init.js"></script>
    
</body>

</html>
