<?php

/**
 *	Name:			Changelogger
 *	Description: 	Create easily changelog files for your projects
 *
 *	Author:			ANEX
 *	Author URL:		http://anex.at
 *
 *	Version:		1.1.0
 */

if( file_exists('app/settings.php' ) )
	require_once( 'app/settings.php' );
	
if( file_exists('app/functions.php' ) )
	require_once( 'app/functions.php' );
	
if( file_exists('app/debug.php' ) )
	require_once( 'app/debug.php' );
	
//====================================================================//
// Do not edit below here
//====================================================================//

$errorstack = array();



//$version = APP_VERSION;

$x = isset( $_GET['x'] ) ? $_GET['x'] : FALSE;

if( isset( $_POST['password'] ) ) {
	
	if( $_POST['password'] == PASSWORD ) { 
		setcookie( APP_TITLE . '_login', sha256( PASSWORD . $_SERVER['REMOTE_ADDR'] ), NULL, '/', '.' . str_ireplace( 'www.', '', $_SERVER['SERVER_NAME'] ) ); 
		header( "Location: " . $_SERVER['PHP_SELF'] ); 
		exit;
	} else { 
		header( "Location: " . $_SERVER['PHP_SELF'] . "?x=wp" ); 
		exit; 
	}
	
}
?>

<!DOCTYPE html>
<html>

    <head>
    
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="robots" content="noindex, nofollow" />
        
        <title><?php echo changelogger_info( 'name' ); ?></title>
        
        <link rel="stylesheet" id="uikit-css"  href="<?php echo APP_BASE_URL; ?>/app/assets/css/uikit/uikit.min.css" type="text/css" media="all" />
        <link rel="stylesheet" id="uikit-css"  href="<?php echo APP_BASE_URL; ?>/app/assets/css/uikit/addons/uikit.addons.min.css" type="text/css" media="all" />
        
        <link rel="stylesheet" id="changelogger-css"  href="<?php echo APP_BASE_URL; ?>/app/assets/css/base.css?<?php echo changelogger_info( 'version' ); ?>" type="text/css" media="all" />
        
	</head>
    
	<?php if(isset($_COOKIE[APP_TITLE . '_login'])) $login = $_COOKIE[APP_TITLE . '_login']; else $login = 'no'; ?>

    
	<?php 
    if( MODE == 'private' ) {
        
        if( $login != sha256( PASSWORD . $_SERVER['REMOTE_ADDR'] ) ) {
            
            include('app/views/login.php');
            
            exit;
            
        }
    }
    ?>

    
    <?php
    //!Generate the change log if need be
    $logfile = CHANGELOG_PATH . 'changelog-' . strtolower( APP_TITLE ) . '.txt';
    
    //!load vars
    $log = array();
    $error = FALSE;
    $lastType = 'update';
    $showFullPaths = isset($_GET['fullPaths']) ? $_GET['fullPaths'] : 0;
    $showRE = isset($_GET['showRE']) ? $_GET['showRE'] : 0;
    $anchor = isset($_GET['anchor']) ? explode('+', str_ireplace('_', ' ', $_GET['anchor'])) : FALSE;
    $q = isset($_GET['q']) ? str_ireplace(' ', '(.*)', $_GET['q']) : '';
    
    // generate file */
    if( !file_exists( $logfile ) )
        file_put_contents( $logfile, '#' . APP_TITLE . ' - Changelog. Generated by Changelogger v ' . changelogger_info( 'version' ) . ' on ' . date( "Y-m-d H:i:s" ) );
    
    //!Load User Details
    if(isset($_COOKIE[APP_TITLE . '_user'])) {
        $userdata = explode('#', base64_decode($_COOKIE[APP_TITLE . '_user']));
        $name = $userdata[0];
        $email = $userdata[1];
        $project = "";
        $version = "";
    }
    else {
        $name = "";
        $email = "";
        $project = "";
        $version = "";
    }
    
    //!Read File
    if(!changelogger_errored()) {
        
        //load log
        $file = file($logfile);
        $REmatch = array();
    
        //!Read file
        foreach($file as $num => $logLine) {
    
            //find entries
            if(preg_match("/^[0-9\-]{10}/", $logLine)) {
                $entry = explode("  ", $logLine);
                $date = $entry[0];
                $name = $entry[3];
                $email = str_ireplace(array("<", ">"), '', trim($entry[4]));
                $project = $entry[1];
                $version = $entry[2];
    
                if(!isset($log[$date])) $log[$date] = array();
                $log[$date][$name]['id'] = array('email' => $email);
    
                $currentDate = $date;
                $currentName = $name;
            }
            //find nodes
            elseif (preg_match("/^\t\*/", $logLine)) {
                $node = explode(' [', str_ireplace("\t* ", '', $logLine));
                $loc = reset($node);
                $loc = explode(":", trim($loc));
                $str = end($node);
                $str = explode("] : ", trim($str));
    
                $text = str_ireplace("\'", "'", trim($str[1]));
    
                //Find RE's
                if (preg_match("/re:[a-z0-9\-\+\_]+/i", $text, $match)) {
                    $REdata = explode('+', str_ireplace(array('re:', '_'), array('', ' '), $match[0]));
    
                    if (!in_array('', $REdata)) {
                        if(!isset($REmatch[$REdata[0]])) $REmatch[$REdata[0]] = array();
                        if(!isset($REmatch[$REdata[0]][$REdata[1]])) $REmatch[$REdata[0]][$REdata[1]] = array();
                        $REmatch[$REdata[0]][$REdata[1]][$REdata[2]] = TRUE;
                    }
                }
                $log[$currentDate][$currentName][] = array(
                    'path' 		=> $loc[0], 
                    'line' 		=> $loc[1], 
                    'type' 		=> $str[0], 
                    'text' 		=> $text
                );
            }
    
    
        }
        $log = array_reverse($log);
    
    }
    
    //! Write
    if( isset( $_POST['sub'] ) ) {
        
        $name 		= isset($_POST['name']) ? $_POST['name'] : "";
        $email 		= isset($_POST['email']) ? $_POST['email'] : "";
        $project 	= isset($_POST['project']) ? $_POST['project'] : "";
        $version 	= isset($_POST['version']) ? $_POST['version'] : "";
        $type 		= isset($_POST['type']) ? $_POST['type'] : "";
        $lastType 	= $type;
        $path 		= isset($_POST['path']) ? $_POST['path'] : "Global";
        $line 		= isset($_POST['line']) ? $_POST['line'] : "N/A";
        $text 		= isset($_POST['text']) ? $_POST['text'] : "";
    
        //Remember && Validate
        if($name != "" && $email != "") setcookie(APP_TITLE . '_HMCLuser', base64_encode($name . '#' . $email), NULL, '/', '.' . str_ireplace('www.', '', $_SERVER['SERVER_NAME']));
        else changelogger_error('You didn\'t provide a name or email');
        
        if($text == "") changelogger_error('You forgot to enter a log message');
        
        //!write to change log
        if(!changelogger_errored()) {
    
            $log[date('Y-m-d')][$name]['id'] = array('email' => $email);
            $log[date('Y-m-d')][$name][] = array(
                    'path' 		=> $path, 
                    'line' 		=> $line, 
                    'type' 		=> $type, 
                    'text' 		=> str_ireplace(array("\'", '\"'), array("'", '"'), $text)
            );
            
            ksort($log);
            
            $toWrite = '';
            $fp = fopen($logfile, "w");
            foreach($log as $date => $users) {
                foreach($users as $name => $nodes) {
                    $toWrite .= "\n" . $date . '  ' . $project . '  ' . $version . '  ' . $name . '  <' . $nodes['id']['email'] . '>' . "\n";
                    unset($nodes['id']);
    
                    foreach($nodes as $node) {
                        $toWrite .= "\t" . '* [' . $node['type'] . '] : ' . $node['path'] . ':' . $node['line'] . ' : ' . $node['text'] . "\n";
                    }
                }
    
            }
            fwrite($fp, str_ireplace(array("\'", '\"'), array("'", '"'), $toWrite));
            fclose($fp);
        }
    }
    ?>

    <?php include('app/views/interface.php'); ?>

</html>
